import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic
import Mathlib.NumberTheory.LSeries.RiemannZeta
import Mathlib.NumberTheory.Harmonic.ZetaAsymp
import Mathlib.MeasureTheory.Integral.CircleIntegral
import Mathlib.MeasureTheory.Integral.Gamma
import Mathlib.Analysis.MellinTransform

#check tsum_subtype
#check HasSum.tsum_eq
#check Summable.hasSum
#check HasSum.add
#check HasSum.sub
#check Filter.Tendsto.add
#check tendsto_atTop
#check tendsto_order
#check Metric.tendsto_atTop
#check Finset.sum_eq_single
#check Finset.sum_comm
#check Finset.sum_congr
#check Finset.mem_image
#check Finset.sum_eq_zero
#check Finset.sum_le_sum
#check tsum_congr
#check HasSum.tsum_eq
#check Summable.tsum_eq
#check tsum_eq_tsum
#check tsum_eq_supr_sum
#check Summable.tsum_le_tsum
#check Summable.tsum_le_tsum_of_nonneg
#check Finset.range
#check Finset.mem_range
#check Finset.max'
#check Finset.sup'_eq_sup
#check Finset.sup
#check Finset.le_sup
#check Finset.sup_le_iff
#check Finset.exists_max_image
#check Set.Finite.sup
#check Summable.mul_left
#check Summable.mul_right
#check summable_quadratic_over_geometric
#check tendsto_nhds
#check tendsto_const_nhds
#check tendsto.sub
#check tendsto.add
#check nhdsWithin_le_nhds
#check le_of_lt
#check lt_of_le_of_lt
#check abs_lt
#check abs_of_nonneg
#check sq_abs
#check div_le_div_of_nonneg_right
#check one_div_le_one_div
#check one_div
#check sub_eq_of_eq_add
#check eq_sub_iff_add_eq
#check sub_nonneg
