# -*- coding: utf-8 -*-
"""Step 1-3: K = Q(theta), theta^3 - 16 theta + 16 = 0 — full arithmetic.

KEY FIX: dK = 148, not 9472.  O_K = Z[u] with u = theta^3/8 = 2*theta - 2,
g(u) = u^3 + 6u^2 - 52u + 8 is 2-Eisenstein.  conductor c = 8.
2 is totally ramified (2 O_K = p2^3), 37 splits (1,1,2).
Class group: Minkowski bound = (6/27)*sqrt(148) ~ 2.70 => generated by p2, p2^3=(2).
Units: rank r1+r2-1 = 3+0-1 = 2 (totally real).
"""
import sympy as sp
import mpmath as mp

mp.mp.dps = 50
x = sp.symbols('x')
f = x**3 - 16*x + 16
u = sp.symbols('u')
g = u**3 + 6*u**2 - 52*u + 8

# --- 1. Eisenstein check & dK ---
print("=== 1. O_K, discriminant ===")
print("disc(g) =", sp.discriminant(g, u), "(expect 148)")
print("dK = 148, c = sqrt(disc(f)/dK) =", sp.sqrt(sp.Integer(9472)/148))
print("g Eisenstein at 2:", all(sp.Integer(c).p ** -1 < 1 for c in [6, -52, 8]) if False else
      (sp.Integer(6) % 2 == 0 and sp.Integer(-52) % 2 == 0 and sp.Integer(8) % 2 != 0 and sp.Integer(8) % 4 != 0))

# --- 2. prime ideal decomposition ---
print("\n=== 2. splitting ===")
print("f mod 2 = x^3  -> 2 totally ramified, 2 O_K = p2^3 (e=3,f=1)")
fac37 = sp.factor_list(f, modulus=37)
print("f mod 37:", [(str(a), e) for a, e in fac37[1]], "-> 37 = p37_1 * p37_2^2")
print("Minkowski bound M = (6/27)*sqrt(148) =", mp.mpf(6)/27*mp.sqrt(148))

# roots
th = [mp.mpf(str(r)) for r in sp.nroots(f, n=50)]
u_r = [2*t - 2 for t in th]
print("theta roots:", [mp.nstr(t, 10) for t in th])
print("u roots   :", [mp.nstr(t, 10) for t in u_r])
print("check g(u_i) = 0:", all(abs(sp.N(sp.simplify(g.subs(u, sp.Float(mp.nstr(r, 30)))), 15)) < mp.mpf('1e-25') for r in u_r))

# --- 3. class group: is p2 principal? solve N(a + b u + c u^2) = +-2 ---
# norm via companion: N(w) with w = a + b u + c u^2
# Use matrix representation: multiplication by u on basis 1,u,u^2.
def mulmat(a, b, c):
    # (a + b u + c u^2) * (1, u, u^2)
    # u^3 = -6u^2 + 52u - 8 ; u^4 = u*u^3
    # build via poly ring
    return None

# direct norm formula with sympy
a, b, c = sp.symbols('a b c')
w = a + b*u + c*u**2
# norm = resultant? Use product over conjugates with symbolic roots is messy;
# instead compute norm via matrix of multiplication by w.
# basis 1, u, u^2:
# w*1 = a + b u + c u^2
# w*u = a u + b u^2 + c u^3 = -8c + (a+52c) u + (b-6c) u^2
# w*u^2 = a u^2 + b u^3 + c u^4 ; u^3 = -6u^2+52u-8 ; u^4 = u*u^3 = u(-6u^2+52u-8)
#   = -6u^3 + 52u^2 - 8u = -6(-6u^2+52u-8) + 52u^2 - 8u = 36u^2 - 312u + 48 + 52u^2 - 8u
#   = 88u^2 - 320u + 48
# w*u^2 = a u^2 + b(-6u^2+52u-8) + c(88u^2-320u+48)
#   = (-8b + 48c) + (52b - 320c) u + (a - 6b + 88c) u^2
M = sp.Matrix([
    [a, b, c],
    [-8*c, a + 52*c, b - 6*c],
    [-8*b + 48*c, 52*b - 320*c, a - 6*b + 88*c],
])
Nm = sp.expand(M.det())
print("\n=== 3. class group: p2 principal? ===")
print("norm(a+bu+cu^2) =", sp.factor(Nm))
# search small integer solutions of Nm = +-2
sols = []
for A in range(-12, 13):
    for B in range(-12, 13):
        for C in range(-12, 13):
            v = int(sp.N(Nm.subs({a: A, b: B, c: C})))
            if abs(v) == 2:
                sols.append((A, B, C, v))
print("N = +-2 integer solutions (|coeff|<=12):", sols)
if not sols:
    print("=> no small generator; h(K) likely 3 (p2 nonprincipal), else larger search")
    for A in range(-30, 31):
        for B in range(-30, 31):
            for C in range(-30, 31):
                v = int(sp.N(Nm.subs({a: A, b: B, c: C})))
                if abs(v) == 2:
                    sols.append((A, B, C, v))
    print("extended search (|coeff|<=30):", sols)

# --- 4. units: N = +-1 ---
print("\n=== 4. units (rank 2) ===")
units = []
for A in range(-60, 61):
    for B in range(-60, 61):
        for C in range(-60, 61):
            v = int(sp.N(Nm.subs({a: A, b: B, c: C})))
            if abs(v) == 1:
                units.append((A, B, C, v))
print("N = +-1 integer solutions (|coeff|<=60):", units)
