name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Lean
        uses: leanprover/setup-lean@v1
      - name: Fetch dependencies
        run: lake update
      - name: Build project
        run: lake build
