name: Build and test

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install elan
        run: |
          curl https://elan.lean-lang.org/elan-init.sh -sSf | sh -s -- --default-toolchain none
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: Cache .lake
        uses: actions/cache@v4
        with:
          path: .lake
          key: ${{ runner.os }}-lake-${{ hashFiles('lakefile.toml', 'lean-toolchain') }}

      - name: Fetch dependencies
        run: lake update

      - name: Build project
        run: lake build
